---
postMerge :
  preRun: 
    command:
      - npm install  
      - npm run bootstrap
      - npm run lint
      
  
  subModules:          #Not to be changed
      
        
      - name: geofire-common      
        path : "./packages/geofire-common/"
        pattern: 
          - "./test/Main.test.ts"
        
        framework : mocha
        parallelism: 2

        
        configFile : "./test/mocha.opts"
        
      - name: geofire      
        path : "./packages/geofire/"
        pattern: 
          - "./test/*.test.ts"
        

        
        framework : mocha
      
        parallelism: 3

        configFile : "./test/mocha.opts"  
      
        
      
        

  
version : 2.0.1
